{{- if .Values.serviceAccount.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.serviceAccountName }}
  namespace: yuki-duckdb
  annotations:
    eks.amazonaws.com/role-arn: {{ required "AWS role arn must be set" .Values.serviceAccount.roleARN }}
{{- end }}