{{- if .Values.app.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: yuki-duckdb
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Release.Name }}-{{ .Release.Revision }}
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
data:
  .duckdbrc: {{ list
    ".mode trash"
    "INSTALL httpserver FROM community;"
    "INSTALL iceberg;"
    "INSTALL httpfs;"
    "LOAD httpserver;"
    "CREATE OR REPLACE SECRET secret (TYPE s3, PROVIDER credential_chain);"
    (printf "SELECT httpserve_start('0.0.0.0', %d, '%s');" (int64 .Values.app.container.port) (randAlphaNum 16))
    | join "\n" | b64enc }}
{{- end }}