{{- if and .Values.fabric.enabled .Values.fabric.engines.duckdb.deploy }}
{{- $key := include "proxy.duckdb.apiKey" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fabric.engines.duckdb.name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Values.fabric.engines.duckdb.name }}
    app.kubernetes.io/version: {{ .Release.Name }}-{{ .Release.Revision }}
    app: {{ .Values.fabric.engines.duckdb.name }}
    group: {{ .Values.app.group }}
data:
  api-key: {{ $key | b64enc }}
  .duckdbrc: {{ include "proxy.duckdb.config" (dict "root" . "key" $key) | b64enc }}
{{- end }}
