{{- if and .Values.fabric.enabled .Values.fabric.engines.duckdb.deploy .Values.fabric.engines.duckdb.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fabric.engines.duckdb.serviceAccountName }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "fabric.engines.duckdb.roleARN is required" .Values.fabric.engines.duckdb.roleARN }}
{{- end }}
