{{- if and .Values.fabric.enabled .Values.fabric.engines.duckdb.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.fabric.engines.duckdb.name }}-secret
  labels:
    app.kubernetes.io/name: {{ .Values.fabric.engines.duckdb.name }}
    app.kubernetes.io/version: {{ .Release.Name }}-{{ .Release.Revision }}
    app: {{ .Values.fabric.engines.duckdb.name }}
    group: {{ .Values.app.group }}
data:
  api-key: {{ include "proxy.duckdb.apiKey" . | b64enc }}
  .duckdbrc: {{ include "proxy.duckdb.config" . | b64enc }}
{{- end }}
