{{- if and (hasKey .Values "serviceAccount") .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.serviceAccountName }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleARN }}
{{- end }}