{{- if .Values.passthrough.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-passthrough
  labels:
    app: {{ .Values.app.name }}-passthrough
    group: {{ .Values.app.group }}
spec:
  type: {{ .Values.passthrough.service.type }}
  selector:
    app: {{ .Values.app.name }}-passthrough
  ports:
    - name: app
      port: {{ .Values.passthrough.service.port }}
      targetPort: {{ .Values.passthrough.port }}
{{- end }}
