{{- if .Values.service_account.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-service-account
  namespace: {{ .Values.app.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.service_account.role_arn }}
{{- end}}