apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Release.Name }}-{{ .Release.Revision }}
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  type: {{ .Values.app.service.type }}
  selector:             
    app: {{ .Values.app.name }}
  ports:
    - name: app
      port: {{ .Values.app.service.port }}       
      targetPort: {{ .Values.app.container.port }}
      {{- if .Values.app.service.prometheus.enabled}}
    - name: metric
      port: 9090
      targetPort: 9090
      {{- end}}