name: Publish Helm Chart

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Add dependencies
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update
          find charts -name 'Chart.yaml' -exec dirname {} \; | xargs -I {} helm dependency update {}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"