name: Release Charts

on:
  push:
    branches:
      - main
      - '*'  # Trigger on any branch push

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add Helm repositories
        run: |
          helm repo add external-secrets https://charts.external-secrets.io
          helm repo update

      - name: Determine version strategy
        id: version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "strategy=release" >> $GITHUB_OUTPUT
            echo "is_main=true" >> $GITHUB_OUTPUT
          else
            echo "strategy=prerelease" >> $GITHUB_OUTPUT
            echo "is_main=false" >> $GITHUB_OUTPUT
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

      - name: Auto-bump version (main branch only)
        if: steps.version.outputs.is_main == 'true'
        run: |
          # Get current version from Chart.yaml
          CURRENT_VERSION=$(grep '^version:' charts/yuki/Chart.yaml | awk '{print $2}')
          echo "Current version: $CURRENT_VERSION"
          
          # Parse version components
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          # Increment patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
          
          echo "New version: $NEW_VERSION"
          
          # Update Chart.yaml
          sed -i "s/^version: .*/version: $NEW_VERSION/" charts/yuki/Chart.yaml
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        id: bump

      - name: Create pre-release version (non-main branches)
        if: steps.version.outputs.is_main == 'false'
        run: |
          # Get current version from Chart.yaml
          CURRENT_VERSION=$(grep '^version:' charts/yuki/Chart.yaml | awk '{print $2}')
          SHORT_SHA="${{ steps.version.outputs.short_sha }}"
          
          # Parse version components and increment patch for pre-release
          IFS='.' read -ra VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          # Increment patch version for pre-release
          NEW_PATCH=$((PATCH + 1))
          NEXT_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
          
          # Create pre-release version
          PRERELEASE_VERSION="${NEXT_VERSION}-${SHORT_SHA}"
          echo "Pre-release version: $PRERELEASE_VERSION (based on next version $NEXT_VERSION)"
          
          # Update Chart.yaml with pre-release version
          sed -i "s/^version: .*/version: $PRERELEASE_VERSION/" charts/yuki/Chart.yaml
          
          echo "prerelease_version=$PRERELEASE_VERSION" >> $GITHUB_OUTPUT
        id: prerelease

      - name: Update chart dependencies
        run: |
          find charts -name 'Chart.yaml' -exec dirname {} \; | xargs -I {} helm dependency update {}

      - name: Commit version changes (main branch only)
        if: steps.version.outputs.is_main == 'true'
        run: |
          git add charts/yuki/Chart.yaml
          git commit -m "chore: bump chart version to ${{ steps.bump.outputs.new_version }} [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Run chart-releaser (main branch)
        if: steps.version.outputs.is_main == 'true'
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Package and create pre-release (non-main branches)
        if: steps.version.outputs.is_main == 'false'
        run: |
          mkdir -p .cr-release-packages
          
          # Package the chart
          helm package charts/yuki --destination .cr-release-packages
          
          # Create GitHub pre-release
          PRERELEASE_VERSION="${{ steps.prerelease.outputs.prerelease_version }}"
          TAG_NAME="proxy-${PRERELEASE_VERSION}"
          
          # Create release
          gh release create "$TAG_NAME" \
            --title "Pre-release $TAG_NAME" \
            --notes "Pre-release for branch ${{ github.ref_name }} (commit ${{ github.sha }})" \
            --prerelease \
            .cr-release-packages/*.tgz
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Update Helm repository index (non-main branches)
        if: steps.version.outputs.is_main == 'false'
        run: |
          # Stash any local changes
          git stash push -m "Stash pre-release version changes"
          
          # Checkout gh-pages branch
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          
          # Download the packaged chart from the release
          PRERELEASE_VERSION="${{ steps.prerelease.outputs.prerelease_version }}"
          TAG_NAME="proxy-${PRERELEASE_VERSION}"
          
          # Download the chart file
          gh release download "$TAG_NAME" --pattern "*.tgz"
          
          # Update the Helm repository index
          helm repo index . --url https://yukitechnologies.github.io/yuki-proxy-chart --merge index.yaml
          
          # Commit and push the updated index
          git add index.yaml "proxy-${PRERELEASE_VERSION}.tgz"
          git commit -m "Add pre-release ${PRERELEASE_VERSION} to Helm repository"
          git push origin gh-pages
          
          # Switch back to original branch
          git checkout -
          
          # Restore stashed changes (optional, since this is a temporary CI environment)
          git stash pop || echo "No stash to pop"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
