name: Prepare Helm Release
on:
  push:
    branches:
      - main
      - '*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.stable.json

  release-prerelease:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # same action, different config-file
          config-file: .release-please-config.prerelease.json